eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #注册中心的地址
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

spring:
  application:
    name: consumer #服务的名字

server:
  port: 8082

feign:
  hystrix:
    enabled: true
